### PR TITLE
twitter auto post

### PR DESCRIPTION
**Pull request by meghedi**
Auto Post To Twitter From CMS After Article Publish to Sports

### CODE REVIEW

**Comment by gdbrown** [comment]
@meghedi @efjacobson this has more scenarios to handle since the id of the notification itself is generated based on the content so it can only occur once (in createTwitterNotification).  this is quite possible be a site specific config that is its own watcher entirely you can do multiple apps and handle the different ids.  as this is now, it won't function due to duplicate ids.

we had discussed this a long long time ago and tabled it due to the complicates around content routing to twitter accounts and its being fairly site specific, not a generic capability.  thoughts?

**Comment by gdbrown** [comment]
@meghedi @efjacobson there was also some discussion about if all articles go to all twitter accounts or if just some, some to just sports, etc. etc.  in this scenario all articles go to all twitter accounts which is not a universal scenario.  this feels very site specific.  happy to discuss on slack to brainstorm.

**Comment by efjacobson** [comment]
@gdbrown these are the notes i have from when we first discussed it

- change getApp to getApps (at triniti level it will return the same single app, but as an array)
- pass the result of getApps into notifyTwitter and notify for each
- change the sendAt job id from `"{$nodeRef}.post-tweet"` to `"{$nodeRef}.{$appRef}.post-tweet"`
- use the app ref to generate the notification's id so separate ones are unique
- change the title of the notification based on the app (if two are created with the same title in a short period of time, the second one will be ignored because the system thinks it is a dupe). pass in the app to createTwitterNotification and concat the title with the article title, something like that

looks like this still needs the title/id update but other than that the logic to decide which articles post to which acounts will be in the site level override

**Comment by gdbrown** [comment]
@efjacobson sounds familiar yes.  i think the content routing aspect is site specific but can be done with a custom getApps for sure.  pass the app into the createTwitterNotification to handle the custom id/title which can be generic.

**Comment by efjacobson** [comment]
moved to https://github.com/triniti/core-php/pull/17 because it needs to be sub v2

**Comment by meghedi** [comment]
https://github.com/triniti/core-php/pull/17 is the same but its from a branch less than version 2.

**Pull request closed without merging**
