### PR TITLE
Send notification lock

### PR DESCRIPTION
**Pull request by bhsiao55**
* Add process lock to `Triniti\Notify\SendNotificationHandler`

### CODE REVIEW

**Review by gdbrown — CHANGES_REQUESTED** [review]
@bhsiao55 this might not address the issue if the notification ref would be different if apple news watcher created more than one.  do we know if it's the same notification ref being fired to "send" that creates the issue or no?  also, is this really just apple news that has this problem and should we do this in the apple news notifier only?

need to think more deeply about this but my gut says this might not fix it.  i might be wrong though, what do you think?

**Comment by bhsiao55** [comment]
@gdbrown when i was analyzing the articles that failed, a lot of them were memba him articles with large galleries that were scheduled publish with no other update to the article afterwards.  This leads me to believe that there is only one notification being created and there is two send notification command being sent.  If you look at the raw view of the notification sent event and notification failed event they both have the same node_ref tmz:apple-news-notification:f83cbbc4-4574-4801-9454-a443f7f4d001.  My guess is the first send command is taking so long cause of the number of images so the notification-sent event doesn't get a chance to cancel the job before another send command is sent by the scheduler for the same notification.

**Comment by gdbrown** [comment]
@bhsiao55 but what is sending the notification again?  is the "send" lambda which is executed by the state machine failing or timing out which causes the state machine retry to occur?  check the lambda and state machine logs for those and see what you can find.

**Comment by bhsiao55** [comment]
@gdbrown ok I will take a look.  Can you refresh my memory on what those logs are called?

**Comment by gdbrown** [comment]
something like /aws/lambda/vendor-env-pbjx-send in cloudwatch logs and state machines are in step functions console

**Comment by bhsiao55** [comment]
@gdbrown I looked at the state machine log and you can see LambdaFunctionScheduled twice in the execution events history.  The first time it returns POST_TO_PBJX_FAILED error and looks like it is scheduled again.  When the second request is started, it looks like it gets aborted in 6 seconds.  Here is what I am looking at https://console.aws.amazon.com/states/home?region=us-east-1#/executions/details/arn:aws:states:us-east-1:345746658229:execution:tmz-prod-pbjx-scheduler-v1:9873c62d-0506-4ff6-8b7c-b44398bf9682

**Comment by bhsiao55** [comment]
this code change will not fix the issue.  going to reduce number of max photos for gallery instead

**Pull request closed without merging**
